name: Discord Notification

on:
  pull_request:
    types: [opened]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to Discord
      uses: Ilshidur/action-discord@2.1.0
      with:
        content: 'A new pull request has been opened!'
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
